version: '3.9'
services:
  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./src:/server/src
      - ./test:/server/test
    depends_on:
      - redis
      - database
    networks:
      - app-network

  database:
    image: postgres:15
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  postgres-data:
  redis-data:


networks:
  app-network:
    driver: bridge
